version: '2.0'
services:
  everyday:
    build: 
      context: '.'
    command: ["python3", "periodic_run.py"]
    restart: unless-stopped
    network_mode: "host"
    volumes:
        - ./:/home/vacancy_downloader/
        - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-file: "100"
        max-size: "1000m"
    mem_limit: 2048m
